﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using Refit;
using System.Text;
using System.Threading.Tasks;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace PivotJot
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIPivotalTrackerApi : IPivotalTrackerApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIPivotalTrackerApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<List<Project>> GetProjects(string token)
        {
            var arguments = new object[] { token };
            return (Task<List<Project>>) methodImpls["GetProjects"](Client, arguments);
        }

        public virtual Task PostStory(string token,int projectId,Story story)
        {
            var arguments = new object[] { token,projectId,story };
            return (Task) methodImpls["PostStory"](Client, arguments);
        }

        public virtual Task<User> Authorize(string authorization)
        {
            var arguments = new object[] { authorization };
            return (Task<User>) methodImpls["Authorize"](Client, arguments);
        }

    }
}


